### ISSUE TITLE
" thread 'main' panicked at 'called `Result::unwrap()` on an `Err` " when using bash as shell

### ISSUE THREAD

**Issue by mehedirm6244** [mdgaziur/ferx#1]
The fetch tool works perfect when I use it with zsh as shell. But when I use bash, I get the following error:
![image](https://user-images.githubusercontent.com/86041547/132531368-a836bdff-f26e-40ad-bc40-0533ecc583a1.png)

I believe that this error is for the following lines of code:
![image](https://user-images.githubusercontent.com/86041547/132531511-10fc8f05-d641-494d-bbe2-c0a8c0e48843.png)

Output of `zsh --version`
![image](https://user-images.githubusercontent.com/86041547/132531917-bed36699-3754-4b08-b940-c74b05cfb100.png)

Output of `bash --version`
![image](https://user-images.githubusercontent.com/86041547/132531987-048b6382-78b9-42a0-9a73-840e92cb85bd.png)

**Comment by mdgaziur** [comment]
Can you give me the output of $HOME?

Also, please check if ~/.config/ferx/ has two files called "Arch Linux.txt" and "universal.txt"

**Comment by mdgaziur** [comment]
I think I should make the shell grabber only take the first line of the output of `$SHELL --version`

**Comment by mdgaziur** [comment]
Also, you can see that the error says "No such file or directory" in main.rs. Which means there's something else causing the problem.

**Comment by mdgaziur** [comment]
Ahh, I see. You are using root to run the program. That makes the $HOME directory to be /root. And /root doesn't have `.config/ferx/arts` directory with necessary arts. I need to somehow make it independent on it's arts. Probably gonna add the art files in the code rather than separate files

**Comment by mehedirm6244** [comment]
I guess it's the reason. Also please consider that shell-thingy, as it might cause bugs later?
BTW you're so prooooo, teach me, senpai

**Comment by mdgaziur** [comment]
umm, I'll check shell thingy after a disaster happens :3. btw, I'm not a pro. Also, suggest me a dir. Should I put stuff on /opt/ferx and symlink?
